// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc3tzsLYigdk48mXrTf3Perqpn-0pE3Bg',
    appId: '1:602963135074:web:4f10110f7e44651d7dd052',
    messagingSenderId: '602963135074',
    projectId: 'canlipazar-b3697',
    authDomain: 'canlipazar-b3697.firebaseapp.com',
    databaseURL:
        'https://canlipazar-b3697-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canlipazar-b3697.firebasestorage.app',
    measurementId: 'G-6195VT77GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3tzsLYigdk48mXrTf3Perqpn-0pE3Bg',
    appId: '1:602963135074:android:b0cbc1cc689532af461f3b',
    messagingSenderId: '602963135074',
    projectId: 'canlipazar-b3697',
    databaseURL:
        'https://canlipazar-b3697-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canlipazar-b3697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqjZiF_PjYTDcpbtvUaorv9uk2chdp8is',
    appId: '1:602963135074:ios:2e66bfd02a522a80461f3b',
    messagingSenderId: '602963135074',
    projectId: 'canlipazar-b3697',
    databaseURL:
        'https://canlipazar-b3697-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canlipazar-b3697.firebasestorage.app',
    iosBundleId: 'com.canlipazar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqjZiF_PjYTDcpbtvUaorv9uk2chdp8is',
    appId: '1:602963135074:ios:2e66bfd02a522a80461f3b',
    messagingSenderId: '602963135074',
    projectId: 'canlipazar-b3697',
    databaseURL:
        'https://canlipazar-b3697-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'canlipazar-b3697.firebasestorage.app',
    iosClientId:
        '602963135074-947gsnkgc9so4shs08qtrnrave4n0j9a.apps.googleusercontent.com',
    iosBundleId: 'com.canlipazar.app',
  );
}
